### PR TITLE
Use system properties for requests

### PR DESCRIPTION
**Pull request by Lyyy**
## Description
Regarding [HttpComponents documentation](https://www.javadoc.io/doc/org.apache.httpcomponents/httpclient/4.4/org/apache/http/impl/client/HttpClientBuilder.html), this allows for example to make requests using a proxy.

## Changes
* ![ADD] Use system properties for web requests

[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:http://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:http://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:http://resources.atlas.wooga.com/icons/icon_update.svg "Update"

[BREAK]:http://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:http://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:http://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:http://resources.atlas.wooga.com/icons/icon_webGL.svg "Web:GL"

### CODE REVIEW

**Review by Larusso — APPROVED** [review]
Looks fine for me. Thanks!

**Comment by Lyyy** [comment]
Thanks @Larusso :) Do you plan to release a new plugin version any time soon? Because I'm sadly I'm unable to use your plugin without this fix for my project :/

**Comment by Larusso** [comment]
@Lyyy I have one other PR that I want to merge before release.

**Comment by Larusso** [comment]
@Lyyy https://github.com/wooga/atlas-appcenter/releases/tag/v1.1.0 there you go.

**Comment by Lyyy** [comment]
Thanks a lot! 🥇

**Pull request merged**
